name: ultrasound
channels:
  - defaults
dependencies:
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.2.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=0.8.3
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - icc_rt=2022.1.0
  - icu=73.1
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - nest-asyncio=1.5.6
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openjpeg=2.4.0
  - openssl=3.0.12
  - packaging=23.1
  - pandas=2.1.1
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3.1
  - platformdirs=3.10.0
  - ply=3.11
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtgraph=0.13.1
  - pyserial=3.5
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pywin32=305
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - scipy=1.11.3
  - seaborn=0.12.2
  - setuptools=68.0.0
  - sip=6.7.12
  - six=1.16.0
  - spyder-kernels=2.4.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.7.1
  - tzdata=2023c
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.41.2
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
